# Generated by Django 2.1.5 on 2019-01-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=200)),
                ('animal_race', models.CharField(max_length=200)),
                ('animal_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement_text', models.CharField(max_length=200)),
                ('disponibilite', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Etat'),
        ),
        migrations.AddField(
            model_name='animal',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Lieu'),
        ),
    ]
